[project]
authors = ["Miki Vanoušek <vanousekmikulas@gmail.com>"]
channels = ["conda-forge"]
name = "demo"
platforms = ["linux-64", "osx-arm64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
delta-sharing-python = ">=1.0.5,<2"
pyspark = ">=3.5.5,<4"
python = "3.9.*"
ipykernel = ">=6.29.5,<7"
pandas = ">=2.2.3,<3"
findspark = ">=2.0.1,<3"
setuptools = ">=75.8.2,<76"
matplotlib = ">=3.9.4,<4"
