[project]
authors = ["Miki Vanoušek <vanousekmikulas@gmail.com>"]
channels = ["conda-forge"]
name = "start2025"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.10.*"
ipykernel = ">=6.29.5,<7"
ipywidgets = ">=8.1.5,<9"
pytorch-gpu = ">=1.11.0,<2"
