apiVersion: v1
kind: Pod
metadata:
  name: analytics-simulation
  namespace: analytics
spec:
  nodeSelector:
    poolTypeName: standard  
  containers:
  - name: git
    image: alpine/git:v2.30.2
    command:
    - cat
    tty: true
  - name: python
    image: python:3.9-slim
    command:
    - cat
    tty: true
  - name: builder
    image: gcr.io/kaniko-project/executor:v1.6.0-debug
    imagePullPolicy: Always
    command:
    - /busybox/cat
    tty: true
    env:
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: /var/secrets/google/key.json
    volumeMounts:
    - name: gcp-key
      mountPath: "/var/secrets/google"
  volumes:
  - name: gcp-key
    secret:
      secretName: 'ar-push-key'
