pipeline {
  agent {
    kubernetes {
      defaultContainer "git"
      yamlFile 'ci-environment.yaml'
    }
  }
  environment {
    registry = "europe-west1-docker.pkg.dev/belimo-artifacts/belimo-analytics"
    image_name = "belimo-cloud-simulation"
    GIT_COMMIT_SHORT = sh(
      script: "printf \$(git rev-parse --short ${GIT_COMMIT})",
      returnStdout: true)
    GIT_TAG = sh(
      script: "git tag --contains",
      returnStdout: true).trim()
    UNIX_EPOCH_SECONDS = sh(
      script: "date +%s",
      returnStdout: true)
  }
  stages {
    stage('Setup') {
      steps {
        container('python') {
          // install requirements
          sh 'pip install --no-cache-dir -r requirements.txt'
          sh 'pip install .'
        }
      }
    }
    stage('Unit Tests') {
      steps {
        container('python') {
          sh 'python -m unittest discover -s tests/ -p "test_*.py"'
        }
      }
    }
    stage('Build Image') {
      steps {
        container('builder') {
          sh """
          /kaniko/executor \
          -f `pwd`/Dockerfile \
          -c `pwd` \
          --destination=${registry}/${image_name}:sha-${GIT_COMMIT_SHORT}-${UNIX_EPOCH_SECONDS} \
          """
        }
      }
    }
    stage('Build Tagged Image') {
      when { tag 'v*' }
      steps {
        container('builder') {
          sh """
          /kaniko/executor \
          -f `pwd`/Dockerfile \
          -c `pwd` \
          --destination=${registry}/${image_name}:${GIT_TAG} \
          """
        }
      }
    }
  }
}
